---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: oh-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
        - name: default-token-t9v8q
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: oh-config-map
data:
  FLASK_CONFIG: "prod"
  FLASK_ENV: "production"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oh-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: oh-prod-ip
    networking.gke.io/managed-certificates: oh-cert